import type { NextConfig } from "next";
import createMDX from "@next/mdx";
import fs from "fs";
import path from "path";

// Generate type definitions for article slugs at startup
function generateArticleSlugs() {
  try {
    const articlesDirectory = path.join(process.cwd(), "content/artykuly");
    if (!fs.existsSync(articlesDirectory)) {
      return;
    }

    const fileNames = fs.readdirSync(articlesDirectory);
    const slugs = fileNames
      .filter(
        (fileName) => fileName.endsWith(".md") || fileName.endsWith(".mdx"),
      )
      .map((fileName) => fileName.replace(/\.mdx?$/, ""))
      .sort();

    const outputContent = `// This file is auto-generated by next.config.ts. Do not edit.
export const ARTICLE_SLUGS = ${JSON.stringify(slugs, null, 2)} as const;

export type ArticleSlug = typeof ARTICLE_SLUGS[number];
`;

    const outputPath = path.join(process.cwd(), "lib/article-slugs.ts");

    // Only write if the content actually changed to avoid triggering unnecessary restarts
    let existingContent = "";
    if (fs.existsSync(outputPath)) {
      existingContent = fs.readFileSync(outputPath, "utf8");
    }

    if (existingContent !== outputContent) {
      const libDir = path.dirname(outputPath);
      if (!fs.existsSync(libDir)) {
        fs.mkdirSync(libDir, { recursive: true });
      }
      fs.writeFileSync(outputPath, outputContent, "utf8");
    }
  } catch (error) {
    console.error("Error generating article slugs:", error);
  }
}

generateArticleSlugs();

const nextConfig: NextConfig = {
  pageExtensions: ["js", "jsx", "md", "mdx", "ts", "tsx"],
  images: {
    qualities: [80, 90, 100],
  },
};

const withMDX = createMDX({
  extension: /\.(md|mdx)$/,
  options: {
    remarkPlugins: ["remark-frontmatter"],
  },
});

export default withMDX(nextConfig);
